plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bestsarkariresult.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.bestsarkariresult.app'
        minSdk 23
        targetSdk 35
        versionCode 13
        versionName '3.4.0-deeplink'
    }

    buildTypes {
        debug {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'com.onesignal:OneSignal:[5.6.1, 5.9.99]'
    implementation 'androidx.core:core:1.15.0'
}
